name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.403' 

      - name: Restore dependencies
        run: dotnet restore ./IntroProject.Tests/IntroProject.Tests.csproj

      - name: Build
        run: dotnet build --configuration Release ./IntroProject.Tests/IntroProject.Tests.csproj

      - name: Run unit tests
        run: dotnet test --no-build --configuration Release --verbosity normal ./IntroProject.Tests/IntroProject.Tests.csproj